version: '3.9'
services:
  app:
    container_name: db-service
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - mongo-db
  mongo-db:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: demo
